---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: policy-subscription
  namespace: open-cluster-management
  annotations:
    apps.open-cluster-management.io/github-path: policies
spec:
  channel: open-cluster-management/policy-channel
  placement:
    local: true
