apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-opentlc-cluster-cert
  namespace: oauth-policies
placementRef:
  name: opentlc-cluster-cert-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: opentlc-cluster-cert-policy 
  kind: Policy
  apiGroup: policy.open-cluster-management.io
