apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-connected-cluster-1-cert
  namespace: oauth-policies
placementRef:
  name: connected-cluster-1-cert-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: connected-cluster-1-cert-policy 
  kind: Policy
  apiGroup: policy.open-cluster-management.io
