---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentlc-cluster-github-path
  namespace: open-cluster-management
data:
    path: clusters/opentlc-cluster/manifests
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: opentlc-cluster-subscription
  namespace: open-cluster-management
spec:
  channel: open-cluster-management/policy-channel
  placement:
    local: true
  packageFilter:
    filterRef:
      name: opentlc-cluster-github-path
