apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-auth-provider
  namespace: oauth-policies
spec:
  complianceType: mustonlyhave
  remediationAction: enforce
  disabled: true
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-auth-provider
      spec:
        object-templates:
        - complianceType: mustonlyhave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: OAuth
            metadata:
              name: cluster
            spec:
              identityProviders:
              - htpasswd:
                  fileData:
                    name: htpass-secret
                mappingMethod: claim
                name: htpasswdidp
                type: HTPasswd
              tokenConfig:
                accessTokenMaxAgeSeconds: 7776000
        - complianceType: mustonlyhave
          objectDefinition:
            apiVersion: v1
            data:
              htpasswd: "YWRtaW46JDJ5JDA1JEYvMXdIY2dlbVdnTEJJNzRvYXc2WWV5b3FqMG9OSlh2ZG52eWtiVkREVU9sSjJrSWpkbzdDCmhhcnNoaWw6JDJ5JDA1JGVVNFNsN1BQc2hxN1RTanh3dG5BMS56TnVEcGw3V25COWkxZElhYzFyc2dLNlY3VElMdmNxCg=="
            kind: Secret
            metadata:
              name: htpass-secret
              namespace: openshift-config
            type: Opaque
